export const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM'
export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM'
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN'
export const SORT_ITEMS: 'SORT_ITEMS' = 'SORT_ITEMS'

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST'  = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED'

export const POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST' = 'POST_LOGIN_REQUEST'
export const POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS' = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED: 'POST_LOGIN_FAILED' = 'POST_LOGIN_FAILED'
export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD'

export const MODAL_INGREDIENT_OPEN: 'MODAL_INGREDIENT_OPEN' = 'MODAL_INGREDIENT_OPEN'
export const MODAL_INGREDIENT_CLOSE: 'MODAL_INGREDIENT_CLOSE' = 'MODAL_INGREDIENT_CLOSE'
export const LINK_INGREDIENT_OPEN: 'LINK_INGREDIENT_OPEN' = 'LINK_INGREDIENT_OPEN'

export const POST_LOGOUT_REQUEST: 'POST_LOGOUT_REQUEST' = 'POST_LOGOUT_REQUEST'
export const POST_LOGOUT_SUCCESS: 'POST_LOGOUT_SUCCESS' = 'POST_LOGOUT_SUCCESS'
export const POST_LOGOUT_FAILED: 'POST_LOGOUT_FAILED' = 'POST_LOGOUT_FAILED'

export const MODAL_ORDER_OPEN: 'MODAL_ORDER_OPEN' = 'MODAL_ORDER_OPEN'
export const MODAL_ORDER_CLOSE: 'MODAL_ORDER_CLOSE' = 'MODAL_ORDER_CLOSE'
export const GET_ORDER_DETAILS_REQUEST: 'GET_ORDER_DETAILS_REQUEST' = 'GET_ORDER_DETAILS_REQUEST'
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' = 'GET_ORDER_DETAILS_FAILED'

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED'

export const GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST' = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS' = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILED: 'GET_ORDERS_FAILED' = 'GET_ORDERS_FAILED'

export const MODAL_INFO_ORDER_OPEN: 'MODAL_INFO_ORDER_OPEN' = 'MODAL_INFO_ORDER_OPEN'
export const MODAL_INFO_ORDER_CLOSE: 'MODAL_INFO_ORDER_CLOSE' = 'MODAL_INFO_ORDER_CLOSE'
export const LINK_OPEN_INFO_ORDER: 'LINK_OPEN_INFO_ORDER' = 'LINK_OPEN_INFO_ORDER'

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';

export const WS_CONNECTION_PROFILE_ORDERS_START: 'WS_CONNECTION_PROFILE_ORDERS_START' = 'WS_CONNECTION_PROFILE_ORDERS_START'
export const WS_GET_USER_ORDERS: 'WS_GET_USER_ORDERS' = 'WS_GET_USER_ORDERS'
export const WS_CONNECTION_USER_SUCCESS: 'WS_CONNECTION_USER_SUCCESS' = 'WS_CONNECTION_USER_SUCCESS';
export const WS_CONNECTION_USER_ERROR: 'WS_CONNECTION_USER_ERROR' = 'WS_CONNECTION_USER_ERROR';
export const WS_CONNECTION_USER_CLOSED: 'WS_CONNECTION_USER_CLOSED' = 'WS_CONNECTION_USER_CLOSED';